### ISSUE TITLE
Noise level setting for DRUNet.

### ISSUE THREAD

**Issue by dhryougit** [ZhaomingKong/Denoising-Comparison#4]
Thank you for your great comparison results. 
I have a question about how do you set the noise level in real noise dataset when using DRUNet. 
The network like DRUNet need noise level for input, and in real noise dataset, I cannot find any information about the noise level map.
How did you set this?

**Comment by ZhaomingKong** [comment]
Hi, that is a good question. We have articulated related settings in our manuscript (section 4.1.1).

4.1.1 Experimental Settings
Therefore, a more practical way is to selectively adopt effective pretrained models or predefined parameter settings. Since many DNN methods offer two to six pretrained models with different parameter settings for testing, for fair comparison, we select
the input noise level for each Gaussian denoiser from four different values, which may be regarded as the equivalance of four pretrained models corresponding to low, medium-low, medium-high and high denoising modes. We report the best
average values of all compared methods on each dataset. Peak signal-to-noise ratio (PSNR) and structural similarity
(SSIM) [209] are employed for objective evaluations. 

For DRUNet, we select the best noise level for input from 20 to 60.

**Comment by dhryougit** [comment]
Thank you for your reply!
